# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'



jobs:
- job: BuildLinux
  continueOnError: false
  timeoutInMinutes: 5
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: dotnet restore --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet test --configuration $(buildConfiguration)
    displayName: 'dotnet test $(buildConfiguration)'
# - job: BuildWindows
#   continueOnError: false
#   timeoutInMinutes: 5
#   pool:
#     vmImage: windows-latest
#   steps:
#   - script: dotnet build --configuration $(buildConfiguration)
#     displayName: 'dotnet build $(buildConfiguration)'

#   - script: dotnet test --configuration $(buildConfiguration)
#     displayName: 'dotnet test $(buildConfiguration)'
