# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  imageName: 'pipelines-italo-customer-docker'
  containerRegistry: 'DockerHub-Italo'
  imageRepository: 'italoduarte1991/italo-customer-api'

parameters:
- name: vmImage
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
- name: runTests
  displayName: Run Tests
  type: boolean
  default: true

jobs:
- job: Build
  displayName: Build and Test
  continueOnError: false
  timeoutInMinutes: 3
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:

  - script: echo building $(Build.BuildNumber) with ${{ parameters.vmImage }}
    displayName: 'Pool vm-image'

  - ${{ if eq(parameters.runTests, true) }}:
    - task: DotNetCoreCLI@2
      displayName: 'Unit test'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

  - task: Docker@2
    name: build
    condition: succeeded()
    displayName: Build image Docker
    inputs:
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageRepository)'
      command: 'build'
      Dockerfile: 'Dockerfile'
      tags: 'latest'
    
  - task: Docker@2
    name: push
    condition: succeeded()
    displayName: Push image Docker
    inputs:
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageRepository)'
      command: 'push'
      tags: 'latest'
  

