# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

parameters:
- name: vmImage
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
- name: runTests
  displayName: Run Tests
  type: boolean
  default: true

jobs:
- deployment: DeployAPI
  environment: 'customer-api-dev'
- job: Build
  displayName: Build and Test
  continueOnError: false
  timeoutInMinutes: 5
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.vmImage }}
    displayName: 'pool vm-image'
    
  - task: DotNetCoreCLI@2
    displayName: 'build'
    inputs:
      command: 'build'

  - ${{ if eq(parameters.runTests, true) }}:
    - task: DotNetCoreCLI@2
      displayName: 'test'
      inputs:
        command: 'test'
  - task: DotNetCoreCLI@2
    displayName: 'pack'
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'off'

- job: Publish
  dependsOn:
  - Build
  displayName: Publish 
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'