# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

parameters:
- name: vmImage
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
- name: runTests
  displayName: Run Tests
  type: boolean
  default: true

jobs:
- deployment: DeployAPI
  environment: 'customer-api-dev'
- job: Build
  displayName: Build and Test
  continueOnError: false
  timeoutInMinutes: 5
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.vmImage }}
    displayName: 'pool vm-image'

  - script: dotnet restore
    displayName: 'dotnet restore'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
  # - script: dotnet build --configuration $(buildConfiguration)
  #   displayName: 'dotnet build $(buildConfiguration)'

  - ${{ if eq(parameters.runTests, true) }}:
    - script: dotnet test --configuration $(buildConfiguration)
      displayName: 'dotnet test $(buildConfiguration)'
- job: Publish
  dependsOn:
  - Build
  displayName: Publish 
  steps:
  - script: echo implement publish
    displayName: 'Publishing'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'